// If you update the models, you also need to update the models in the src/models.js file
export const models = [
  {
    name: 'gemini-2.5-flash',
    family: 'gemini',
    displayName: 'Gemini 2.5 Flash',
    displayNameV2: '2.5 Flash',
    capabilities: ['vision', 'internet'],
    description: 'Fast Gemini model with vision and web search.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'google/gemini-2.5-flash-preview-05-20',
  },
  {
    name: 'gemini-2.5-pro',
    family: 'gemini',
    displayName: 'Gemini 2.5 Pro Vision',
    displayNameV2: '2.5 Pro Vision',
    capabilities: ['vision', 'internet', 'thinking'],
    description: 'Pro version with advanced reasoning, vision, and web search. Experimental.',
    reasoning: true,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'google/gemini-2.5-pro-exp-03-25',
  },
  {
    name: 'gpt-imagegen',
    family: 'chatgpt',
    displayName: 'GPT ImageGen',
    displayNameV2: 'ImageGen',
    capabilities: ['vision', 'imagegen'],
    description: 'GPT model for image generation and vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/gpt-imagegen',
  },
  {
    name: 'o4-mini',
    family: 'chatgpt',
    displayName: 'O4 Mini',
    displayNameV2: 'O4 Mini',
    capabilities: ['vision', 'thinking'],
    description: 'Mini O4 model with vision and reasoning.',
    reasoning: true,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/o4-mini',
  },
  {
    name: 'claude-4-sonnet',
    family: 'claude',
    displayName: 'Claude 4 Sonnet',
    displayNameV2: '4 Sonnet',
    capabilities: ['vision'],
    description: 'Claude 4 Sonnet with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'anthropic/claude-sonnet-4',
  },
  {
    name: 'claude-4-sonnet-reasoning',
    family: 'claude',
    displayName: 'Claude 4 Sonnet Reasoning',
    displayNameV2: '4 Sonnet Reasoning',
    capabilities: ['reasoning', 'vision', 'thinking'],
    description: 'Claude 4 Sonnet with advanced reasoning, vision, and thinking.',
    reasoning: true,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: true,
    freeAccess: false,
    openRouterName: 'anthropic/claude-sonnet-4',
  },
  {
    name: 'deepseek-r1',
    family: 'deepseek',
    displayName: 'DeepSeek R1',
    displayNameV2: 'R1 (reasoning)',
    capabilities: ['thinking'],
    description: 'DeepSeek R1 with advanced reasoning.',
    reasoning: true,
    experimental: false,
    additionalInfo: 'deepseek',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'deepseek/deepseek-r1:free',
  },
  {
    name: 'gemini-2.0-flash',
    family: 'gemini',
    displayName: 'Gemini 2.0 Flash',
    displayNameV2: '2.0 Flash',
    capabilities: ['vision', 'internet'],
    description: 'Gemini 2.0 Flash with vision and web search.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'google/gemini-2.0-flash-001',
  },
  {
    name: 'gemini-2.0-flash-lite',
    family: 'gemini',
    displayName: 'Gemini 2.0 Flash Lite',
    displayNameV2: '2.0 Flash Lite',
    capabilities: ['vision'],
    description: 'Lite version of Gemini 2.0 Flash with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'google/gemini-2.0-flash-lite-001',
  },
  {
    name: 'gemini-2.5-flash-thinking',
    family: 'gemini',
    displayName: 'Gemini 2.5 Flash Thinking',
    displayNameV2: '2.5 Flash Thinking',
    capabilities: ['thinking', 'vision', 'internet'],
    description: 'Experimental Gemini 2.5 Flash with advanced thinking, vision, and web search.',
    reasoning: true,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'google/gemini-2.5-flash-preview-05-20',
  },
  {
    name: 'gpt-4o-mini',
    family: 'chatgpt',
    displayName: 'GPT-4o Mini',
    displayNameV2: '4o Mini',
    capabilities: ['vision'],
    description: 'Mini version of GPT-4o with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/gpt-4o-mini',
  },
  {
    name: 'gpt-4o',
    family: 'chatgpt',
    displayName: 'GPT-4o',
    displayNameV2: '4o',
    capabilities: ['vision'],
    description: 'GPT-4o with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/chatgpt-4o-latest',
  },
  {
    name: 'gpt-4.1',
    family: 'chatgpt',
    displayName: 'GPT-4.1',
    displayNameV2: '4.1',
    capabilities: ['vision'],
    description: 'GPT-4.1 with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/gpt-4.1',
  },
  {
    name: 'gpt-4.1-mini',
    family: 'chatgpt',
    displayName: 'GPT-4.1 Mini',
    displayNameV2: '4.1 Mini',
    capabilities: ['vision'],
    description: 'Mini version of GPT-4.1 with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'openai/gpt-4.1-mini',
  },
  {
    name: 'gpt-4.1-nano',
    family: 'chatgpt',
    displayName: 'GPT-4.1 Nano',
    displayNameV2: '4.1 Nano',
    capabilities: ['vision'],
    description: 'Nano version of GPT-4.1 with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'openai/gpt-4.1-nano',
  },
  {
    name: 'gpt-o3-mini',
    family: 'chatgpt',
    displayName: 'GPT O3 Mini',
    displayNameV2: 'O3 Mini',
    capabilities: [],
    description: 'Mini version of GPT O3.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/o3-mini',
  },
  {
    name: 'gpt-o3',
    family: 'chatgpt',
    displayName: 'GPT O3',
    displayNameV2: 'O3',
    capabilities: ['vision', 'thinking'],
    description: 'GPT O3 with vision and advanced thinking.',
    reasoning: true,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'openai/o3',
  },
  {
    name: 'gpt-o3-pro',
    family: 'chatgpt',
    displayName: 'GPT o3 Pro',
    displayNameV2: 'o3 Pro',
    capabilities: ['vision', 'thinking'],
    description: 'GPT O3 with vision and advanced thinking.',
    reasoning: true,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: true,
    freeAccess: false,
    openRouterName: 'openai/o3-pro',
  },
  {
    name: 'claude-3.5-sonnet',
    family: 'claude',
    displayName: 'Claude 3.5 Sonnet',
    displayNameV2: '3.5 Sonnet',
    capabilities: ['vision'],
    description: 'Claude 3.5 Sonnet with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'anthropic/claude-3.5-sonnet',
  },
  {
    name: 'claude-3.7-sonnet',
    family: 'claude',
    displayName: 'Claude 3.7 Sonnet',
    displayNameV2: '3.7 Sonnet',
    capabilities: ['vision'],
    description: 'Claude 3.7 Sonnet with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'anthropic/claude-3.7-sonnet',
  },
  {
    name: 'claude-3.7-sonnet-reasoning',
    family: 'claude',
    displayName: 'Claude 3.7 Sonnet Reasoning',
    displayNameV2: '3.7 Sonnet Reasoning',
    capabilities: ['reasoning', 'vision', 'thinking'],
    description: 'Claude 3.7 Sonnet with advanced reasoning, vision, and thinking.',
    reasoning: true,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: true,
    freeAccess: false,
    openRouterName: 'anthropic/claude-3.7-sonnet:thinking',
  },
  {
    name: 'claude-4-opus',
    family: 'claude',
    displayName: 'Claude 4 Opus',
    displayNameV2: '4 Opus',
    capabilities: ['vision'],
    description: 'Claude 4 Opus with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: true,
    freeAccess: false,
    openRouterName: 'anthropic/claude-opus-4',
  },
  {
    name: 'llama-3.3-70b-experimental',
    family: 'llama',
    displayName: 'Llama 3.3 70B',
    displayNameV2: '3.3 70B',
    capabilities: [],
    description: 'Experimental Llama 3.3 70B.',
    reasoning: false,
    experimental: true,
    additionalInfo: 'llama distilled',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'shisa-ai/shisa-v2-llama3.3-70b:free',
  },
  {
    name: 'llama-4-scout',
    family: 'llama',
    displayName: 'Llama 4 Scout',
    displayNameV2: '4 Scout',
    capabilities: ['vision'],
    description: 'Experimental Llama 4 Scout with vision.',
    reasoning: false,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'meta-llama/llama-4-scout:free',
  },
  {
    name: 'llama-4-maverick',
    family: 'llama',
    displayName: 'Llama 4 Maverick',
    displayNameV2: '4 Maverick',
    capabilities: ['vision'],
    description: 'Experimental Llama 4 Maverick with vision.',
    reasoning: false,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'meta-llama/llama-4-maverick:free',
  },
  {
    name: 'deepseek-v3-0324',
    family: 'deepseek',
    displayName: 'DeepSeek V3 0324',
    displayNameV2: 'V3 0324',
    capabilities: [],
    description: 'Experimental DeepSeek V3 0324.',
    reasoning: false,
    experimental: true,
    additionalInfo: 'deepseek',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'deepseek/deepseek-chat-v3-0324:free',
  },
  {
    name: 'deepseek-r1-0528-thinking',
    family: 'deepseek',
    displayName: 'DeepSeek R1 0528 Thinking',
    displayNameV2: 'R1 0528 Thinking',
    capabilities: ['thinking'],
    description: 'Experimental DeepSeek R1 0528 with advanced thinking.',
    reasoning: true,
    experimental: true,
    additionalInfo: 'deepseek',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'deepseek/deepseek-r1-zero:free',
  },
  {
    name: 'deepseek-r1-qwen-distilled',
    family: 'deepseek',
    displayName: 'DeepSeek R1 Qwen Distilled',
    displayNameV2: 'R1 Qwen Distilled',
    capabilities: [],
    description: 'DeepSeek R1 distilled with Qwen.',
    reasoning: false,
    experimental: false,
    additionalInfo: 'qwen distilled',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'deepseek/deepseek-r1-0528-qwen3-8b:free',
  },
  {
    name: 'grok-3',
    family: 'grok',
    displayName: 'Grok 3',
    displayNameV2: 'Grok 3',
    capabilities: [],
    description: 'Grok 3 model.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'x-ai/grok-3-beta',
  },
  {
    name: 'grok-3-mini-thinking',
    family: 'grok',
    displayName: 'Grok 3 Mini Thinking',
    displayNameV2: '3 Mini Thinking',
    capabilities: ['thinking'],
    description: 'Experimental Grok 3 Mini with advanced thinking.',
    reasoning: true,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'x-ai/grok-3-mini-beta',
  },
  {
    name: 'qwen-qwq-32b-thinking',
    family: 'qwen',
    displayName: 'Qwen QWQ-32B Thinking',
    displayNameV2: 'QWQ-32B Thinking',
    capabilities: ['thinking'],
    description: 'Experimental Qwen QWQ-32B with advanced thinking.',
    reasoning: true,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: true,
    openRouterName: 'deepseek/deepseek-r1-distill-qwen-32b:free',
  },
  {
    name: 'qwen-2.5-32b-vision',
    family: 'qwen',
    displayName: 'Qwen 2.5 32B Vision',
    displayNameV2: '2.5 32B Vision',
    capabilities: ['vision'],
    description: 'Experimental Qwen 2.5 32B with vision.',
    reasoning: false,
    experimental: true,
    additionalInfo: '',
    apiKeyRequired: false,
    freeAccess: false,
    openRouterName: 'qwen/qwen-2.5-32b',
  },
  {
    name: 'gpt-4.5-vision',
    family: 'chatgpt',
    displayName: 'GPT-4.5 Vision',
    displayNameV2: '4.5 Vision',
    capabilities: ['vision'],
    description: 'GPT-4.5 with vision.',
    reasoning: false,
    experimental: false,
    additionalInfo: '',
    apiKeyRequired: true,
    freeAccess: false,
    openRouterName: 'openai/gpt-4.5-preview',
  },
];
